# Default values for flaskapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "alon001.azurecr.io/myapp"
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: myacr-secret

nameOverride: ""
fullnameOverride: ""

ports:
  - name: http
    containerPort: 80
    protocol: TCP


serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

resources:
  requests:
    memory: "2Gi"
  limits:
    memory: "2Gi"

podAnnotations: {}
podLabels:
  app.kubernetes.io/name: flaskapp

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx  # Ensure this matches your Ingress controller
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-production"  # Use letsencrypt-production for real certificates
  hosts:
    - host: alon.ydevops.io  # Your DNS name
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: alon015-flaskapp  # Your service name
              port:
                number: 80
  tls:  # Define the TLS configuration
    - hosts:
        - alon.ydevops.io
      secretName: alon-ydevops-io-tls  # Secret where the certificate will be stored


autoscaling:
  enabled: false

