# Default values for flaskapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "alon001.azurecr.io/myapp"
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: myacr-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

resources:
  requests:
    memory: "2Gi"
  limits:
    memory: "2Gi"

podAnnotations: {}
podLabels: {}

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000
  loadBalancerIP: "your-static-ip-address"

ingress:
  enabled: false


autoscaling:
  enabled: false


volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}