image:
  repository: "alon001.azurecr.io/myflaskapp"
  pullPolicy: always
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
